### ISSUE TITLE
prevent horizontal animation when attaching to a slider

### ISSUE THREAD

**Issue by davefallis** [barvian/number-flow#11]
I am trying to use this library in a way that the `MotionNumber` component moves horizontally as `value` changes, tied to a slider component. What I am observing is that the `MotionNumber` component itself is animating horizontally but I don't want the animation. I just want it to immediately move to the new location without the horizontal animation. Is there a way to stop the animation? I apologize if this is a general framer question. I am still learning the library.

**Comment by barvian** [comment]
Hi, thanks for filing. I agree this is not ideal; I think normally you'd use [`layoutRoot`](https://www.framer.com/motion/layout-animations/###item-is-performing-unwanted-layout-animations-as-surrounding-content-changes) to address this but in my tests that didn't seem to work with MotionNumber. I'm investigating potential solutions 🤔

**Comment by barvian** [comment]
I just launched a rewrite of this library that now includes a slider example supported by a new `isolate` prop: https://number-flow.barvian.me/examples/#slider 🙂
