### ISSUE TITLE
Number positions are misaligned slightly when the animating the position of the container

### ISSUE THREAD

**Issue by daryl** [barvian/number-flow#13]
Hey man,

Not sure if you remember me, but we used to chat like 10+ years ago.

Anyway, this library is absolutely killer.

One thing I've noticed is an issue with number positioning/kerning being temporarily out of sync while the surrounding container is animating.

Hopefully that makes sense, let me know if you need me to expand further.

It's kind of blocking me using it.

**Comment by barvian** [comment]
Hey man,

I definitely remember and I'm a huge fan of your work esp Godly 👋. I think the issue you're seeing might be related to #11. I'm working on a fix for these layout issues but unfortunately it's turning into a pretty big refactor that'll probably take a couple more weeks (I'm busy with work atm). I'd love to get this working in whatever you're building though, so I'd be happy to workshop a temporary solution if you're interested: [max@barvian.me](mailto:max@barvian.me)

**Comment by barvian** [comment]
Alright the refactor turned into a rewrite in WAAPI instead of Framer Motion. Here's the WIP docs for the new package , which is published but I haven't shared it yet: [number-flow.barvian.me](https://number-flow.barvian.me?_vercel_share=PfsvYIArBlLFqlG0uS2GPhCungx6DZHi). I'd love to know if it solves your issue!

**Comment by barvian** [comment]
I just launched the rewrite. It comes with an `isolate` prop which may help in your use case. I'd love to hear your feedback! https://number-flow.barvian.me
