### ISSUE TITLE
possible to go from 0 -> 9 without scrolling through all of the numbers between?

### ISSUE THREAD

**Issue by skoshx** [barvian/number-flow#18]
Hey, loving this library! Also, I saw the NumberFlow rewrite and it looks super cool :)

Anyways, one thing that bothers me is when you go from like 20 -> 19, the first number (2 -> 1) animates smoothly, but second (0 -> 9) animates a bit chaotically because it scrolls "up" through all the numbers. 

Would it be possible to add an option, where 0->9 animates in a way that the 9 comes "from below" instead, aka only one shift would need to be made between 0 and 9. (AFAIK that's how iOS does it to feel more "zen")

I hope my explanation was clear enough :)

Thank you in advance!

**Comment by skoshx** [comment]
PS. If this would be possible to add for instance to NumberFlow as an optional flag or something, I'd love to beta test it!

**Comment by barvian** [comment]
Hi 👋 Do you mean something like this?

https://github.com/user-attachments/assets/32501eb9-5f9f-425d-90cd-faf8773419d0

Coming soon in a big update for NumberFlow ^

**Comment by skoshx** [comment]
Yeah, exactly like that! That's great!!🤩 Please do let me know when you release this for NumberFlow and I'd love to try it out!

**Comment by barvian** [comment]
It's out 🙂 https://number-flow.barvian.me. Please let me know if you run into any issues.
