### ISSUE TITLE
Using 'use-debounce' will cause number not reaching target

### ISSUE THREAD

**Issue by itsdapi** [barvian/number-flow#19]
### Step to reproduce

```tsx
function DebounceMN({ value }: { value: number }) {
  const [dValue] = useDebounce(value, 200);
  return <MotionNumber value={dValue ? dValue : 0} />;
}
```

### Expected result

giving value `12345` will result something like `00045`

**Comment by barvian** [comment]
I just pushed a rewrite of MotionNumber called NumberFlow that should fix this: https://number-flow.barvian.me. Please let me know if you're still experiencing issues 👋
