### ISSUE TITLE
Animation lifecycle events not triggered

### ISSUE THREAD

**Issue by jackleslie** [barvian/number-flow#20]
[Animation events](https://www.framer.com/motion/component/#%23animation-events) like `onAnimationStart` etc don't get triggered when passed as props

I imagine this is because the `{...rest}` spread not being passed to the `motion.span` with the `animate` prop which will include these props

**Comment by barvian** [comment]
Hi, I'm sure this is not the response you were expecting but I just rewrote the library with new `onAnimationsStart` and `onAnimationsFinish` events ([docs](https://number-flow.barvian.me/)). Please let me know if you're still seeing issues with them 👋
