### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by DamianGlowala** [barvian/number-flow#24]
Plan for Vue support has already been mentioned. I've created this issue as a tracker.

Once completed, it might be worth checking whether it works in Nuxt (SSR) too?

**Comment by vuthanhbayit** [comment]
You can try https://www.npmjs.com/package/@vt7/vue-number-flow.

In Nuxt I tried and got an error, I checked if there was a problem in esm-env 
https://github.com/barvian/number-flow/blob/4fe9cebbfcddd992b27896585558357b65b806d6/packages/number-flow/src/ssr.ts#L1

**Comment by DamianGlowala** [comment]
Haven't had a chance to try it out yet, but in my opinion a Nuxt module instead of having to create a plugin would provide better DX :)

**Comment by ishaiavrahami** [comment]
@barvian any update?

**Comment by barvian** [comment]
It's almost there, I just need to convert the examples on the site and do/write more tests 👍

**Comment by barvian** [comment]
By the way, if anybody knows a solution for this it'd be very helpful! https://discord.com/channels/325477692906536972/1299071468533055541

**Comment by barvian** [comment]
Just pushed `@number-flow/vue` (👉 [docs](https://number-flow.barvian.me/vue/)). Please let me know if you experience any issues!

**Comment by ishaiavrahami** [comment]
Just tested and it works perfectly! Great job @barvian

**Comment by larrasu** [comment]
Any update for SSR support?
