### ISSUE TITLE
TypeError on iOS 16.4 Safari 

### ISSUE THREAD

**Issue by leeeunsang-tmobi** [barvian/number-flow#31]
I found a bug.
Thanks for creating a great library.

@number-flow/react@0.2.1

https://github.com/barvian/number-flow/blob/main/packages/number-flow/src/index.ts#L439

```
[Error] The above error occurred in the <NumberFlowImpl> component:

Component@
NumberFlow2
NumberFlow
....
```

```
[Error] TypeError: Type error
	(Anonymous Function) (react-dom.development.js:376)
	callCallback (react-dom.development.js:4164)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:4213)
	invokeGuardedCallback (react-dom.development.js:4277)
	reportUncaughtErrorInDEV (react-dom.development.js:22872)
	captureCommitPhaseError (react-dom.development.js:27160)
	commitLayoutMountEffects_complete (react-dom.development.js:24724)
...
```

**Comment by barvian** [comment]
Yikes, thanks for reporting. Looking into this now

**Comment by barvian** [comment]
OK I think this should be fixed now. It turns out Safari 16.4 supports CSS `mod()` but not `linear()`; I was only checking for `mod()`. Technically this version of Safari could handle a `cubic-bezier` easing so I may add a fallback for that. Please let me know if you're still experiencing issues 👋

**Comment by leeeunsang-tmobi** [comment]
The animation doesn't work, but the error is gone. Thanks.
