### ISSUE TITLE
`esm-env` exports resolution issue in Cloudflare Pages environment

### ISSUE THREAD

**Issue by NOBLES5E** [barvian/number-flow#45]
There's currently an issue with `esm-env` package's exports resolution when running in Cloudflare Pages environment. The problem stems from Cloudflare Pages being treated as a WebWorker environment, which Vite considers as a browser environment. This causes server-side code to incorrectly use browser exports.

**Comment by barvian** [comment]
Hi, thanks for filing this 👋. I just pushed [`@number-flow/react@0.2.4`](https://github.com/barvian/number-flow/releases/tag/%40number-flow%2Freact%400.2.4) with an attempted fix. Please comment if you'e still experiencing issues!

**Comment by barvian** [comment]
@NOBLES5E do you have a link to an issue on Cloudflare/esm-env/Vite for this by chance? I couldn't find anything and it'd be nice to know if it gets resolved 👋

**Comment by NOBLES5E** [comment]
Yes, it is resolved. We use it in an internal project, so no issues can be found on GitHub.

Thank you for the quick fix!

**Comment by barvian** [comment]
Oh, great to hear! I was actually wondering if you had a link to an upstream issue for esm-env on Cloudflare Pages? It sounds like a bug on Cloudflare Pages and I'd like to switch back to esm-env at some point 😄

**Comment by barvian** [comment]
@NOBLES5E Hi, could you try esm-env-runtime@^0.1.1 now?

**Comment by NOBLES5E** [comment]
Everything is working properly now. Really appreciate the quick responses and fixes.

**Comment by denny64** [comment]
@barvian - Hi, has this been fixed for svelte?

**Comment by barvian** [comment]
Hi @denny64 👋🏻, the same solution should apply to Svelte, i.e. add this to your package.json:

```json
"overrides": {
    "esm-env": "npm:esm-env-runtime@^0.1.0"
}
```
