### ISSUE TITLE
[Webpack Module Federation] Failed to execute 'define' on 'CustomElementRegistry': the name "number-flow" has already been used with this registry

### ISSUE THREAD

**Issue by alopeza-gbm** [barvian/number-flow#56]
### NumberFlow version

@number-flow/react@0.2.5

### Framework version

18.3.1

### Describe the bug and the steps to reproduce it

Hi! I have implemented NumberFlow on a React wrapper component, I use this component on other components on the same screen but I get this error: 

 

```
hook.js:608 NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "number-flow" has already been used with this registry
```

**Comment by barvian** [comment]
Hi 👋, would you be able to upgrade to `@number-flow/react@0.3.0` (latest) to see if it's still an issue?

**Comment by alopeza-gbm** [comment]
Hello @barvian! it still fails with the 0.3.0 version :(

I get the same error but with the new element name for React

```
Failed to execute 'define' on 'CustomElementRegistry': the name "number-flow-react" has already been used with this registry
NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "number-flow-react" has already been used with this registry
```

I am using Module Federation and this is probably the reason for the problem, because if I simulate the same without micro frontends, this error does not happen

**Comment by barvian** [comment]
Hey, thanks for the context and the patch. I suppose the class is getting recreated if the identity check fails. I'm not sure all minifiers preserve the constructor name, and theoretically that could collide in a different way, but I also worry that e.g. a Symbol would fail if the identity check does 🤔. I'll have to look more into this. If you have the bandwidth, a repro would be super helpful as I've never used Module Federation 😅

**Comment by alopeza-gbm** [comment]
Hi @barvian, sorry for the wait, I have tried with version `@number-flow/react@0.2.6` and `number-flow@0.3.4` and it worked fine, but I still get the error in console `An element with the name number-flow has already been defined`

Updating to version `@number-flow/react@0.3.0`, this problem appears again, debugging a little, this is because module federation has a configuration that allows to share the depdencias between micro frontends, by default in my project, this is not done this way, so module federation loads a copy for each micro frontend, so when arriving to this line:

https://github.com/barvian/number-flow/blob/4755fa0e652bcea3d5cb4eb2868c4d3bab74ea8c/packages/react/src/index.tsx#L24

https://github.com/barvian/number-flow/blob/4755fa0e652bcea3d5cb4eb2868c4d3bab74ea8c/packages/number-flow/src/util/dom.ts#L42

A new instance is created, thus breaking the condition that prevents it to be redefined

I have created a sample project with this behavior: https://github.com/alopeza-gbm/react-module-federation

Doing some research, I believe this can be solved in this way:

```diff
export const define = (name: string, constructor: CustomElementConstructor) => {
	if (!BROWSER) return
	const RegisteredElement = customElements.get(name)
-	if (RegisteredElement === constructor) return
+	if (RegisteredElement !== undefined) return
	return customElements.define(name, constructor)
}
```

Since the names in the `CustomElementRegistry` are unique and if not found, it returns undefined

**Comment by barvian** [comment]
Hey, no problem and thanks for the extra context 👍. I ran the project locally and can see the issue. Unfortunately I don't think I want to change the behavior in number-flow because it seems to be working as expected; i.e. it should be throwing for a duplicated instance of the component. Is there a way you can dedupe number-flow between micro frontends? I'm gonna close this for now but feel free to respond 👋

**Comment by lili21** [comment]
I have ran into the same issue.   if I visit a page with number-flow, navigate to another page, and click the browser back button. it will throw the error.

**Comment by NOBLES5E** [comment]
This error frequently hits us as well in an AstroJS project.

**Comment by barvian** [comment]
@NOBLES5E hi, can you submit a repro for this? The docs site is built with Astro

**Comment by lili21** [comment]
It doesn't work in micro frontends project.

**Comment by lili21** [comment]
a way to fix this

```jsx
import { useEffect, useRef, useState } from 'react';
import type NumberFlowType from 'number-flow';

export function NumberFlow({ value }: { value: number }) {
  const [isNumberFlowDefined, setIsNumberFlowDefined] = useState(
    !!customElements.get('number-flow'),
  );
  const ref = useRef<NumberFlowType>(null);

  useEffect(() => {
    if (isNumberFlowDefined) {
      return;
    }
    import('number-flow').then(() => {
      setIsNumberFlowDefined(true);
    });
  }, [isNumberFlowDefined]);

  useEffect(() => {
    if (isNumberFlowDefined) {
      ref.current?.update(value);
    }
  }, [value, isNumberFlowDefined]);

  return isNumberFlowDefined ? (
    // @ts-expect-error custom-element
    <number-flow ref={ref}>{value}</number-flow>
  ) : null;
}
```
