### ISSUE TITLE
Build failing on Cloudflare Pages

### ISSUE THREAD

**Issue by sbertix** [barvian/number-flow#68]
### NumberFlow version

number-flow@0.3.9

### Framework version

react@0.3.4

### Describe the bug and the steps to reproduce it

Hey @barvian 👋 

Thank you for this amazing component. 
Unfortunately, number-flow@0.3.9 seems to break the `HTMLElement` definition when using the package on (at least) Cloudflare Pages. 

```
✘ [ERROR] service core:user:console: Uncaught ReferenceError: HTMLElement is not defined

    at null.<anonymous> (hsuxupbtu3d.js:80164:20) in
  ../node_modules/.pnpm/number-flow@0.3.9/node_modules/number-flow/dist/index.mjs
```

Am I missing something that has changed?

**Comment by sbertix** [comment]
> Hi, thanks for filing. This is a duplicate of #45 I think. Could you try adding the following to your package.json?

Apologies, I completely missed the new replies there, and assumed it was unrelated, as the original fix didn't seem to work. 

> ```json
> "overrides": {
>     "esm-env": "npm:esm-env-runtime@^0.1.1"
> }
> ```

Works like a charm. Thank you 🙇‍♂️  

> I think it's also worth reporting a bug with Cloudflare

I think I might be able to ask/notify somebody in the Workers team.

**Comment by barvian** [comment]
No problem! Glad the solution worked for you 😃
