### ISSUE TITLE
NumberFlow Shows No Numbers on Arabic Locale on Safari

### ISSUE THREAD

**Issue by rixuanzheng** [barvian/number-flow#90]
### NumberFlow version

@number-flow/react@0.4.4

### Framework version

react@19

### Describe the bug and the steps to reproduce it

![image](https://github.com/user-attachments/assets/7a1bdbb9-1490-4ca3-901c-e232653a030b)

The numbers are missing when on Safari only when the locale is set to arabic

### Minimal reproduction (greatly appreciated)

https://codesandbox.io/p/sandbox/agitated-elbakyan-l9jgtj

**Comment by barvian** [comment]
Hi 👋, thanks for the repro! It appears that Safari is returning `‏١٬٢٣٤٫٠٠ US$` for this locale whereas Chrome returns `1,234.00 US$`. These numerals aren't currently supported, unfortunately (see #8). Closing in favor of #8 for now.

**Comment by barvian** [comment]
I posted this workaround in #8 but for posterity: you can add `-u-nu-latn` to a locale string to force it to use Latin digits. In this case:

```jsx
<NumberFlow locales="ar-u-nu-latn" />
```

[Sandbox](https://codesandbox.io/p/sandbox/agitated-elbakyan-l9jgtj)
